2019-01-23 02:09:01,747 ERROR: Exception on /auth/login [GET] [in c:\users\anushrut\appdata\local\programs\python\python36\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\users\anushrut\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\anushrut\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\anushrut\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\anushrut\appdata\local\programs\python\python36\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\users\anushrut\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\anushrut\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "F:\workload\flask\flaskProj\app\auth\routes.py", line 26, in login
    return render_template('auth/login.html', title='Sign In', form=form)
  File "c:\users\anushrut\appdata\local\programs\python\python36\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "c:\users\anushrut\appdata\local\programs\python\python36\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "c:\users\anushrut\appdata\local\programs\python\python36\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\anushrut\appdata\local\programs\python\python36\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\anushrut\appdata\local\programs\python\python36\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\anushrut\appdata\local\programs\python\python36\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "F:\workload\flask\flaskProj\app\templates\auth\login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "F:\workload\flask\flaskProj\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\anushrut\appdata\local\programs\python\python36\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\anushrut\appdata\local\programs\python\python36\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\anushrut\appdata\local\programs\python\python36\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\anushrut\appdata\local\programs\python\python36\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "F:\workload\flask\flaskProj\app\templates\base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "F:\workload\flask\flaskProj\app\templates\auth\login.html", line 12, in block "app_content"
    <p>New User? <a href="{{ url_for('register') }}">Click to Register!</a></p>
  File "c:\users\anushrut\appdata\local\programs\python\python36\lib\site-packages\flask\helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\anushrut\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\anushrut\appdata\local\programs\python\python36\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\users\anushrut\appdata\local\programs\python\python36\lib\site-packages\flask\helpers.py", line 323, in url_for
    force_external=external)
  File "c:\users\anushrut\appdata\local\programs\python\python36\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'register'. Did you mean 'auth.register' instead?
2019-01-23 02:11:24,037 INFO: flask Project [in F:\workload\flask\flaskProj\app\__init__.py:73]
2019-01-23 19:11:33,941 INFO: flask Project [in F:\workload\flask\flaskProj\app\__init__.py:75]
2019-01-23 19:13:12,314 INFO: flask Project [in F:\workload\flask\flaskProj\app\__init__.py:75]
2019-01-23 19:13:58,722 INFO: flask Project [in F:\workload\flask\flaskProj\app\__init__.py:75]
2019-01-23 19:14:07,118 INFO: flask Project [in F:\workload\flask\flaskProj\app\__init__.py:75]
2019-01-23 21:42:43,765 INFO: flask Project [in F:\workload\flask\flaskProj\app\__init__.py:81]
2019-01-23 21:43:48,716 INFO: flask Project [in F:\workload\flask\flaskProj\app\__init__.py:81]
2019-01-23 21:44:21,288 INFO: flask Project [in F:\workload\flask\flaskProj\app\__init__.py:81]
2019-01-23 22:08:59,868 INFO: flask Project [in F:\workload\flask\flaskProj\app\__init__.py:81]
